import type { InspectItem } from "@/app/types";

export const inspectItems: InspectItem[] = [
  {
    id: "1",
    no: "01",
    name: "Pablo Reyes",
    company: "Kautzer",
    status: "active",
    lastActivity: "2024-01-15",
    userId : "",
    role: "Senior Developer",
    email: "pablo.reyes@kautzer.com",
  },
  {
    id: "2",
    no: "02",
    name: "Pablo Reyes",
    company: "Powlowski",
    userId : "",
    status: "pending",
    lastActivity: "2024-01-14",
    role: "Product Manager",
    email: "pablo.reyes@powlowski.com",
  },
  {
    id: "3",
    no: "03",
    name: "Ryan Edgar",
    company: "Maggio",
    userId : "",
    status: "completed",
    lastActivity: "2024-01-13",
    role: "UI Designer",
    email: "ryan.edgar@maggio.com",
  },
  {
    id: "4",
    no: "04",
    name: "Bellamy Trejo",
    company: "Not Assigned",
    userId : "",
    status: "pending",
    lastActivity: "2024-01-12",
    role: "Frontend Developer",
    email: "bellamy.trejo@email.com",
  },
  {
    id: "5",
    no: "05",
    name: "Madelynn Fletcher",
    company: "Not Assigned",
    status: "active",
    lastActivity: "2024-01-11",
    userId : "",
    role: "Data Analyst",
    email: "madelynn.fletcher@email.com",
  },
  {
    id: "6",
    no: "06",
    name: "Pablo Reyes",
    userId : "",
    company: "Not Assigned",
    status: "pending",
    lastActivity: "2024-01-10",
    role: "Backend Developer",
    email: "pablo.reyes@email.com",
  },
  {
    id: "7",
    no: "07",
    name: "Madelynn Fletcher",
    company: "Not Assigned",
    userId : "",
    status: "completed",
    lastActivity: "2024-01-09",
    role: "QA Engineer",
    email: "madelynn.fletcher2@email.com",
  },
];
