name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            cybranex/compscope-frontend:${{ github.run_number }}
            cybranex/compscope-frontend:latest
      
      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/compscope
            
            mkdir -p frontend
            
            cat > frontend/.env << 'EOF'
            ${{ secrets.FRONTEND_ENV_CONTENT }}
            EOF
            
            docker pull cybranex/compscope-frontend:latest
            
            docker-compose up -d --no-deps frontend
            
            docker exec nginx nginx -s reload || true
            
            docker image prune -af
            
            docker logs frontend --tail 50
            
            echo "✅ Frontend deployment completed!"
